import type { Provider } from "./models-dev"

export const WPEED_PROVIDERS: Record<string, Provider> = {
  "anthropic": {
    id: "anthropic",
    name: "Anthropic",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "anthropic/claude-3-5-sonnet-20241022": {
        id: "anthropic/claude-3-5-sonnet-20241022",
        name: "Claude 3.5 Sonnet",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-fable-5": {
        id: "anthropic/claude-fable-5",
        name: "Claude Fable 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-fable-latest": {
        id: "anthropic/claude-fable-latest",
        name: "Claude Fable Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-haiku-4-5": {
        id: "anthropic/claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-1": {
        id: "anthropic/claude-opus-4-1",
        name: "Claude Opus 4.1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-20250514": {
        id: "anthropic/claude-opus-4-20250514",
        name: "Claude Opus 4",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-5": {
        id: "anthropic/claude-opus-4-5",
        name: "Claude Opus 4.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-5-reasoning": {
        id: "anthropic/claude-opus-4-5-reasoning",
        name: "Claude Opus 4.5 Reasoning",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-6": {
        id: "anthropic/claude-opus-4-6",
        name: "Claude Opus 4.6",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-7": {
        id: "anthropic/claude-opus-4-7",
        name: "Claude Opus 4.7",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-8": {
        id: "anthropic/claude-opus-4-8",
        name: "Claude Opus 4.8",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-8-fast": {
        id: "anthropic/claude-opus-4-8-fast",
        name: "Claude Opus 4.8 Fast",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-4-8-reasoning": {
        id: "anthropic/claude-opus-4-8-reasoning",
        name: "Claude Opus 4.8 Reasoning",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-opus-latest": {
        id: "anthropic/claude-opus-latest",
        name: "Claude Opus Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-sonnet-4-20250514": {
        id: "anthropic/claude-sonnet-4-20250514",
        name: "Claude Sonnet 4",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-sonnet-4-5": {
        id: "anthropic/claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-sonnet-4-6": {
        id: "anthropic/claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "anthropic/claude-sonnet-5": {
        id: "anthropic/claude-sonnet-5",
        name: "Claude Sonnet 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "openai": {
    id: "openai",
    name: "OpenAI",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "openai/gpt-4-5-mini": {
        id: "openai/gpt-4-5-mini",
        name: "GPT 4.5 Mini",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-4o": {
        id: "openai/gpt-4o",
        name: "GPT 4o",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-4o-mini": {
        id: "openai/gpt-4o-mini",
        name: "GPT 4o Mini",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5": {
        id: "openai/gpt-5",
        name: "GPT 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-1": {
        id: "openai/gpt-5-1",
        name: "GPT 5.1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-1-codex": {
        id: "openai/gpt-5-1-codex",
        name: "GPT 5.1 Codex",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-1-codex-mini": {
        id: "openai/gpt-5-1-codex-mini",
        name: "GPT 5.1 Codex Mini",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-1-mini": {
        id: "openai/gpt-5-1-mini",
        name: "GPT 5.1 Mini",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-3": {
        id: "openai/gpt-5-3",
        name: "GPT 5.3",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-4": {
        id: "openai/gpt-5-4",
        name: "GPT 5.4",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-4-mini": {
        id: "openai/gpt-5-4-mini",
        name: "GPT 5.4 Mini",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-5": {
        id: "openai/gpt-5-5",
        name: "GPT 5.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-6-luna": {
        id: "openai/gpt-5-6-luna",
        name: "GPT 5.6 Luna",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-6-sol": {
        id: "openai/gpt-5-6-sol",
        name: "GPT 5.6 Sol",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-6-sol-pro": {
        id: "openai/gpt-5-6-sol-pro",
        name: "GPT 5.6 Sol Pro",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-6-terra": {
        id: "openai/gpt-5-6-terra",
        name: "GPT 5.6 Terra",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-mini": {
        id: "openai/gpt-5-mini",
        name: "GPT 5 Mini",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-5-nano": {
        id: "openai/gpt-5-nano",
        name: "GPT 5 Nano",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-oss-120b": {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-oss-120b-cloud": {
        id: "openai/gpt-oss-120b-cloud",
        name: "GPT OSS 120B Cloud",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "openai/gpt-oss-20b": {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "google": {
    id: "google",
    name: "Google",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "google/gemini-2-5-flash": {
        id: "google/gemini-2-5-flash",
        name: "Gemini 2.5 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-2-5-flash-lite": {
        id: "google/gemini-2-5-flash-lite",
        name: "Gemini 2.5 Flash Lite",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-2-5-pro": {
        id: "google/gemini-2-5-pro",
        name: "Gemini 2.5 Pro",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-1-flash-lite-preview": {
        id: "google/gemini-3-1-flash-lite-preview",
        name: "Gemini 3.1 Flash Lite Preview",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-1-pro": {
        id: "google/gemini-3-1-pro",
        name: "Gemini 3.1 Pro",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-1-pro-preview": {
        id: "google/gemini-3-1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-5-flash": {
        id: "google/gemini-3-5-flash",
        name: "Gemini 3.5 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-flash": {
        id: "google/gemini-3-flash",
        name: "Gemini 3 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-flash-preview": {
        id: "google/gemini-3-flash-preview",
        name: "Gemini 3 Flash Preview",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-3-pro": {
        id: "google/gemini-3-pro",
        name: "Gemini 3 Pro",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemini-flash-latest": {
        id: "google/gemini-flash-latest",
        name: "Gemini Flash Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemma-4-31b-it": {
        id: "google/gemma-4-31b-it",
        name: "Gemma 4 31B IT",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "google/gemma4": {
        id: "google/gemma4",
        name: "Gemma 4",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "xai": {
    id: "xai",
    name: "xAI",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "xai/grok-3": {
        id: "xai/grok-3",
        name: "Grok 3",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4": {
        id: "xai/grok-4",
        name: "Grok 4",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4-3": {
        id: "xai/grok-4-3",
        name: "Grok 4.3",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4-5": {
        id: "xai/grok-4-5",
        name: "Grok 4.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4-5-high": {
        id: "xai/grok-4-5-high",
        name: "Grok 4.5 High",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4-5-low": {
        id: "xai/grok-4-5-low",
        name: "Grok 4.5 Low",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4-5-medium": {
        id: "xai/grok-4-5-medium",
        name: "Grok 4.5 Medium",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-4-fast-reasoning": {
        id: "xai/grok-4-fast-reasoning",
        name: "Grok 4 Fast Reasoning",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-build": {
        id: "xai/grok-build",
        name: "Grok Build",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-build-0-1": {
        id: "xai/grok-build-0-1",
        name: "Grok Build 0.1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "xai/grok-code-fast-1": {
        id: "xai/grok-code-fast-1",
        name: "Grok Code Fast 1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "deepseek": {
    id: "deepseek",
    name: "DeepSeek",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "deepseek/deepseek-chat": {
        id: "deepseek/deepseek-chat",
        name: "DeepSeek Chat",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-r1": {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-reasoner": {
        id: "deepseek/deepseek-reasoner",
        name: "DeepSeek Reasoner",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v3-1": {
        id: "deepseek/deepseek-v3-1",
        name: "DeepSeek V3 1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v3-1-terminus": {
        id: "deepseek/deepseek-v3-1-terminus",
        name: "DeepSeek V3 1 Terminus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v3-2": {
        id: "deepseek/deepseek-v3-2",
        name: "DeepSeek V3 2",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v4-flash": {
        id: "deepseek/deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v4-flash-search": {
        id: "deepseek/deepseek-v4-flash-search",
        name: "DeepSeek V4 Flash Search",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v4-pro": {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v4-pro-max": {
        id: "deepseek/deepseek-v4-pro-max",
        name: "DeepSeek V4 Pro Max",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "deepseek/deepseek-v4-pro-search": {
        id: "deepseek/deepseek-v4-pro-search",
        name: "DeepSeek V4 Pro Search",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "zhipu": {
    id: "zhipu",
    name: "Z.ai",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "zai/glm-4-5": {
        id: "zai/glm-4-5",
        name: "GLM 4.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-4-5-air": {
        id: "zai/glm-4-5-air",
        name: "GLM 4.5 Air",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-4-6": {
        id: "zai/glm-4-6",
        name: "GLM 4.6",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-4-7": {
        id: "zai/glm-4-7",
        name: "GLM 4.7",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-5": {
        id: "zai/glm-5",
        name: "GLM 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-5-1": {
        id: "zai/glm-5-1",
        name: "GLM 5.1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-5-2": {
        id: "zai/glm-5-2",
        name: "GLM 5.2",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-5-2:nitro": {
        id: "zai/glm-5-2:nitro",
        name: "GLM 5.2 Nitro",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "zai/glm-5-turbo": {
        id: "zai/glm-5-turbo",
        name: "GLM 5 Turbo",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "qwen": {
    id: "qwen",
    name: "Alibaba",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "alibaba/qween3-6-max-preview": {
        id: "alibaba/qween3-6-max-preview",
        name: "Qwen 3 6 Max Preview",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qween3-6-plus": {
        id: "alibaba/qween3-6-plus",
        name: "Qwen 3 6 Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qween3-7-max": {
        id: "alibaba/qween3-7-max",
        name: "Qwen 3 7 Max",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen-3-5-397b": {
        id: "alibaba/qwen-3-5-397b",
        name: "Qwen 3.5 397B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen-3-max": {
        id: "alibaba/qwen-3-max",
        name: "Qwen 3 Max",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen-plus-2025-07-28": {
        id: "alibaba/qwen-plus-2025-07-28",
        name: "Qwen Plus 2025.07.28",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen2-5-7b": {
        id: "alibaba/qwen2-5-7b",
        name: "Qwen 2 5 7B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen2-5-coder-7b-instruct-uncensored-gguf": {
        id: "alibaba/qwen2-5-coder-7b-instruct-uncensored-gguf",
        name: "Qwen 2 5 Coder 7B Instruct Uncensored Gguf",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-235b-a22b": {
        id: "alibaba/qwen3-235b-a22b",
        name: "Qwen 3 235B A22B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-5-122b-a10b": {
        id: "alibaba/qwen3-5-122b-a10b",
        name: "Qwen 3 5 122B A10B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-5-397b-a17b": {
        id: "alibaba/qwen3-5-397b-a17b",
        name: "Qwen 3 5 397B A17B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-5-flash": {
        id: "alibaba/qwen3-5-flash",
        name: "Qwen 3 5 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-5-omni-flash": {
        id: "alibaba/qwen3-5-omni-flash",
        name: "Qwen 3 5 Omni Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-5-omni-plus": {
        id: "alibaba/qwen3-5-omni-plus",
        name: "Qwen 3 5 Omni Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-5-plus": {
        id: "alibaba/qwen3-5-plus",
        name: "Qwen 3 5 Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-6-27b": {
        id: "alibaba/qwen3-6-27b",
        name: "Qwen 3 6 27B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-6-35b-a3b": {
        id: "alibaba/qwen3-6-35b-a3b",
        name: "Qwen 3 6 35B A3B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-6-max-preview": {
        id: "alibaba/qwen3-6-max-preview",
        name: "Qwen 3 6 Max Preview",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-6-plus": {
        id: "alibaba/qwen3-6-plus",
        name: "Qwen 3 6 Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-7-max": {
        id: "alibaba/qwen3-7-max",
        name: "Qwen 3 7 Max",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-7-plus": {
        id: "alibaba/qwen3-7-plus",
        name: "Qwen 3 7 Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-8-max-preview": {
        id: "alibaba/qwen3-8-max-preview",
        name: "Qwen 3 8 Max Preview",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-coder-plus": {
        id: "alibaba/qwen3-coder-plus",
        name: "Qwen 3 Coder Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-max-2026-01-23": {
        id: "alibaba/qwen3-max-2026-01-23",
        name: "Qwen 3 Max 2026.01.23",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-omni-flash-2025-12-01": {
        id: "alibaba/qwen3-omni-flash-2025-12-01",
        name: "Qwen 3 Omni Flash 2025.12.01",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3-vl-plus": {
        id: "alibaba/qwen3-vl-plus",
        name: "Qwen 3 VL Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "alibaba/qwen3p7-plus": {
        id: "alibaba/qwen3p7-plus",
        name: "Qwen 3p7 Plus",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "kimi": {
    id: "kimi",
    name: "Moonshot",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "moonshot/kimi-for-coding": {
        id: "moonshot/kimi-for-coding",
        name: "Kimi For Coding",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-for-coding-highspeed": {
        id: "moonshot/kimi-for-coding-highspeed",
        name: "Kimi For Coding Highspeed",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-k2": {
        id: "moonshot/kimi-k2",
        name: "Kimi K2",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-k2-5": {
        id: "moonshot/kimi-k2-5",
        name: "Kimi K2 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-k2-6": {
        id: "moonshot/kimi-k2-6",
        name: "Kimi K2 6",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-k2-7-code": {
        id: "moonshot/kimi-k2-7-code",
        name: "Kimi K2 7 Code",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-k2-7-code-highspeed": {
        id: "moonshot/kimi-k2-7-code-highspeed",
        name: "Kimi K2 7 Code Highspeed",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "moonshot/kimi-k3": {
        id: "moonshot/kimi-k3",
        name: "Kimi K3",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "minimax": {
    id: "minimax",
    name: "MiniMax",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "minimax/minimax-m2-1": {
        id: "minimax/minimax-m2-1",
        name: "MiniMax M2 1",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "minimax/minimax-m2-5": {
        id: "minimax/minimax-m2-5",
        name: "MiniMax M2 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "minimax/minimax-m2-7": {
        id: "minimax/minimax-m2-7",
        name: "MiniMax M2 7",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "minimax/minimax-m3": {
        id: "minimax/minimax-m3",
        name: "MiniMax M3",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "mistral": {
    id: "mistral",
    name: "Mistral",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "mistral/codestral-latest": {
        id: "mistral/codestral-latest",
        name: "Codestral Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/ministral-14b-instruct-2512": {
        id: "mistral/ministral-14b-instruct-2512",
        name: "Ministral 14B Instruct 2512",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-large-3-675b-instruct-2512": {
        id: "mistral/mistral-large-3-675b-instruct-2512",
        name: "Mistral Large 3 675B Instruct 2512",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-large-latest": {
        id: "mistral/mistral-large-latest",
        name: "Mistral Large Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-medium-3-5": {
        id: "mistral/mistral-medium-3-5",
        name: "Mistral Medium 3.5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-medium-3-5-128b": {
        id: "mistral/mistral-medium-3-5-128b",
        name: "Mistral Medium 3.5 128B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-medium-latest": {
        id: "mistral/mistral-medium-latest",
        name: "Mistral Medium Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-small-4-119b-2603": {
        id: "mistral/mistral-small-4-119b-2603",
        name: "Mistral Small 4 119B 2603",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "mistral/mistral-small-latest": {
        id: "mistral/mistral-small-latest",
        name: "Mistral Small Latest",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "meta": {
    id: "meta",
    name: "Meta",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "meta/llama-3-1-70b-instruct": {
        id: "meta/llama-3-1-70b-instruct",
        name: "Llama 3.1 70B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama-3-1-8b-instruct": {
        id: "meta/llama-3-1-8b-instruct",
        name: "Llama 3.1 8B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama-3-2-1b-instruct": {
        id: "meta/llama-3-2-1b-instruct",
        name: "Llama 3.2 1B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama-3-3-70b-versatile": {
        id: "meta/llama-3-3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama-4-maverick-17b-128e-instruct": {
        id: "meta/llama-4-maverick-17b-128e-instruct",
        name: "Llama 4 Maverick 17B 128E Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama-v3p3-70b-instruct": {
        id: "meta/llama-v3p3-70b-instruct",
        name: "Llama V3p3 70B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama3-2-1b": {
        id: "meta/llama3-2-1b",
        name: "Llama3 2 1B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/llama3-2-3b": {
        id: "meta/llama3-2-3b",
        name: "Llama3 2 3B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "meta/meta-llama-3-3-70b-instruct": {
        id: "meta/meta-llama-3-3-70b-instruct",
        name: "Meta Llama 3.3 70B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "nvidia": {
    id: "nvidia",
    name: "NVIDIA",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "meta/llama-3-3-nemotron-super-49b-v1-5": {
        id: "meta/llama-3-3-nemotron-super-49b-v1-5",
        name: "Llama 3.3 Nemotron Super 49B V1 5",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "nvidia/ising-calibration-1-35b-a3b": {
        id: "nvidia/ising-calibration-1-35b-a3b",
        name: "Ising Calibration 1 35B A3B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "nvidia/nemotron-3-nano-30b-a3b": {
        id: "nvidia/nemotron-3-nano-30b-a3b",
        name: "Nemotron 3 Nano 30B A3B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "nvidia/nemotron-3-super-120b-a12b": {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "Nemotron 3 Super 120B A12B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "nvidia/nemotron-3-ultra-550b-a55b": {
        id: "nvidia/nemotron-3-ultra-550b-a55b",
        name: "Nemotron 3 Ultra 550B A55B",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "nvidia/nemotron-nano-12b-v2-vl": {
        id: "nvidia/nemotron-nano-12b-v2-vl",
        name: "Nemotron Nano 12B V2 VL",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "nvidia/nvidia-nemotron-nano-9b-v2": {
        id: "nvidia/nvidia-nemotron-nano-9b-v2",
        name: "Nvidia Nemotron Nano 9B V2",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
  "other": {
    id: "other",
    name: "Other",
    env: [],
    npm: "@ai-sdk/openai-compatible",
    api: "https://wspeed-flame.vercel.app/v1",
    models: {
      "doubao/seed-oss-36b-instruct": {
        id: "doubao/seed-oss-36b-instruct",
        name: "Seed OSS 36B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "inclusionai/ling-flash-2-0": {
        id: "inclusionai/ling-flash-2-0",
        name: "Ling Flash 2.0",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "sarvamai/sarvam-m": {
        id: "sarvamai/sarvam-m",
        name: "Sarvam M",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "stepfun/step-3-5-flash": {
        id: "stepfun/step-3-5-flash",
        name: "Step 3.5 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "stepfun/step-3-7-flash": {
        id: "stepfun/step-3-7-flash",
        name: "Step 3.7 Flash",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
      "upstage/solar-10-7b-instruct": {
        id: "upstage/solar-10-7b-instruct",
        name: "Solar 10 7B Instruct",
        release_date: "",
        attachment: false,
        reasoning: false,
        temperature: false,
        tool_call: true,
        limit: { context: 128000, output: 8192 },
        provider: { npm: "@ai-sdk/openai-compatible", api: "https://wspeed-flame.vercel.app/v1" },
      },
    },
  },
}
